#pragma config(Sensor, port1,  userSensor,     sensorNone)
#pragma config(Sensor, port3,  touch,          sensorVexIQ_LED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*                        Copyright (c) James Pearman                          */
/*                                   2014                                      */
/*                            All Rights Reserved                              */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    Module:     generic_demo.c                                               */
/*    Author:     James Pearman                                                */
/*    Created:    20 June 2014                                                 */
/*                                                                             */
/*    Revisions:                                                               */
/*                V1.00     5 August 2014 - Initial release                    */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    The author is supplying this software for use with the VEX IQ            */
/*    control system. This file can be freely distributed and teams are        */
/*    authorized to freely use this program , however, it is requested that    */
/*    improvements or additions be shared with the Vex community via the vex   */
/*    forum.  Please acknowledge the work of the authors when appropriate.     */
/*    Thanks.                                                                  */
/*                                                                             */
/*    Licensed under the Apache License, Version 2.0 (the "License");          */
/*    you may not use this file except in compliance with the License.         */
/*    You may obtain a copy of the License at                                  */
/*                                                                             */
/*      http://www.apache.org/licenses/LICENSE-2.0                             */
/*                                                                             */
/*    Unless required by applicable law or agreed to in writing, software      */
/*    distributed under the License is distributed on an "AS IS" BASIS,        */
/*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. */
/*    See the License for the specific language governing permissions and      */
/*    limitations under the License.                                           */
/*                                                                             */
/*    The author can be contacted on the vex forums as jpearman                */
/*    or electronic mail using jbpearman_at_mac_dot_com                        */
/*    Mentor for team 8888 RoboLancers, Pasadena CA.                           */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    This is example RobotC code that can be used with the vex iq             */
/*    reference sensor.  The "user sensor" should be connected to port 1 on    */
/*    the vex iq brain, a touch led should be connected to port 3.  See the    */
/*    VEX IQ Reference Sensor documentation for more details.                  */
/*                                                                             */
/*-----------------------------------------------------------------------------*/



#include "generic_i2c.c"

task main()
{
    char buffer[4];
    int  i;
    portName userPort;

    // Find out generic sensor
    userPort = genericI2cFindFirst();

    // No sensor, then stop here
    while(userPort == -1)
        wait1Msec(10);

    // Static displays
    drawLine(0, 23, 128, 23);
    displayStringAt(55,33,"Deg C");
    displayStringAt(5,20,"Switch :");
    displayStringAt(5,10,"PWM    :");

    while(1)
        {
        // Write led brightness
        buffer[0] = i++;
        genericI2cWrite( userPort, 0x28, buffer, 1 );

        // Read switch and temperature
        genericI2cRead( userPort, 0x24, buffer, 4 );

        // display temperature
        displayBigStringAt(5, 40, "%3.1f", ((float)buffer[0] / 4 ));

        // display switch status
        if( buffer[1] & 1 )
            displayStringAt(55,20,"Released");
        else
            displayStringAt(55,20,"Pressed ");

        // display current pwm value for the led
        displayStringAt(55,10,"%3d", i & 0xFF);

        // run a touch led on port 3 at the same time with the
        // same brightness.
        setTouchLEDRGB( touch, i, 0, 0);

        wait1Msec(5);
        }
}
